### ISSUE TITLE
Proper Documentation

### ISSUE THREAD

**Issue by sajorahasan** [searchy2/CustomPermissionsDialogue#1]
Hello,
Can you please provide installation instruction.
I did try to include library by gradle but my project keeps compiling old version 1.1 works fine though.

Thanks, your library is super awesome. I'm currently using your 2 library in my project i.e. CustomPermissionsDialogue, CustomAlertViewDialog. Same is also happening with CustomAlertViewDialog

**Comment by sajorahasan** [comment]
Working fine now.

**Comment by rayliverified** [comment]
Thanks for using the library :D
I am currently developing apps so I have not had the time to create a proper ReadMe. Will do in a few weeks hopefully! 
This library is the ONLY permissions library that handles ALL permission scenarios. Check out my other repositories too ;)

**Comment by rayliverified** [comment]
Documentation created!
