### ISSUE TITLE
Failed to resolve: com.github.searchy2:CustomPermissionsDialogue:27.1.1

### ISSUE THREAD

**Issue by ParthJadav** [searchy2/CustomPermissionsDialogue#2]
Failed to resolve: com.github.searchy2:CustomPermissionsDialogue:27.1.1

![capture](https://user-images.githubusercontent.com/20708825/39293273-1753d158-4956-11e8-805e-36c3e20ce651.PNG)

**Comment by rayliverified** [comment]
Try using:
`implementation 'com.github.searchy2:CustomPermissionsDialogue:v1.8.1'`
